version: '3'

services:
  sme-api:
    image: iboslimitedbd/#{Deployment}#:#{Build.BuildId}#
    ports:
      - "82:80"
    restart: always
    environment:
      #- #{AppEnvName}#=#{AppEnvValue}#
      - AppEnvName=#{AppEnvName}#
      - AppEnvValue=#{AppEnvValue}#
      - ConnectionString=#{ConnectionString}#
      # Add more environment variables as needed

